version: '3.8'
services:
  production:
    image: postgres
    restart: always 
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  staging:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_DATABASE=DeliveryTest
    ports:
      - "3306:3306"
    